Improvements and bug fixes: sha_lines -> hashcat

diff --git a/ffind b/ffind
--- a/ffind
+++ b/ffind
@@ -1,8 +1,33 @@
 #!/bin/bash
 
+
+usage()
+{
+  local PGM=$(basename $0)
+  echo "Usage: [OPTS] <pattern>"
+  echo "where OPTS:"
+  echo "  -d dir  : specify directory to search (default current dir)"
+  echo "  -t type : specify the type of entry to seek (default f)"
+  echo "  -h      : this help text"
+}
+
 [[ 0 -eq $# ]] && { echo "Nothing to do"; exit 22; }
 
+WHERE=.
+TYPE=f
+while getopts :d:t:h opt
+do
+  case $opt in
+    d) WHERE=$OPTARG ;;
+    t) TYPE=$OPTARG ;;
+    h) usage; exit ;;
+    :) echo "Missing argument for '-$OPTARG'"; exit 22 ;;
+    *) echo "Invalid argument: '-$OPTARG'"; exit 22 ;;
+  esac
+done
+shift $((OPTIND-1))
+
 while [[ $# -ne 0 ]]; do
-  find . -type f -name "$1"
+  find $WHERE -type $TYPE -name "$1"
   shift
 done
diff --git a/sep b/sep
--- a/sep
+++ b/sep
@@ -1,11 +1,46 @@
 #!/bin/bash
 
+usage()
+{
+  local PGM=$(basename $0)
+  echo "Usage: $PGM [OPTS] <char>"
+  echo "Where OPTS:"
+  echo "  -[0-9]+ : specify line count"
+  echo "  -/      : half the screen"
+  echo "  -h      : this help text"
+}
+
+CMDLINES=0
+unset HALF NUM
+while getopts :1234567890/h opt
+do
+  echo "opt: '$opt'"
+  case $opt in
+    [0-9]) NUM=1; CMDLINES=$((CMDLINES*10+opt)) ;;
+        /) HALF=1 ;;
+        h) usage; exit ;;
+    *) echo "ERROR: Unknown option: '-$OPTARG'"; exit 22 ;;
+  esac
+done
+shift $((OPTIND-1))
+echo "CMDLINES: $CMDLINES"
+
+# / and numbers mutally exclusive
+[[ -n $HALF && -n $NUM ]] && { echo "FATAL: count and half cannot be specified together"; exit 22; }
+
+# at most 1 argument (other than options)
+# if no arguments, default sep char is '-'
+# separator MUST be a single char
+[[ $# -gt 1 ]] && { echo "ERROR: Invalid command line"; exit 22; }
 [[ 0 -eq $# ]] && CHR='-' || CHR=$1
-[[ ${#CHR} -ne 1 ]] && { echo "Invalid sepatator: '$CHR'"; exit 22; }
+[[ ${#CHR} -ne 1 ]] && { echo "Invalid separator: '$CHR'"; exit 22; }
 
 # get the number of lines on the screen
-
 [[ -z $LINES ]] && LINES=$(tput lines)
+[[ -n $HALF ]] && CMDLINES=$((LINES/2))
+[[  $CMDLINES -gt 0 ]] && LINES=$CMDLINES
+
+# how many columns
 [[ -z $COLUMNS ]] && COLUMNS=$(tput cols)
 
 [[ -n $LINES ]] && NUM=$LINES || NUM=25
diff --git a/subgrep b/subgrep
--- a/subgrep
+++ b/subgrep
@@ -3,25 +3,38 @@
 usage()
 {
   PGM=$(basename $0)
+  echo "Usage: $PGM [OPTS] <search> [file[s]]"
+  echo "Where OPTS:"
+  echo "  -c     : match c/cpp source files (default all or [files])"
+  echo "  -d dir : specify directory to search (default: .)"
+  echo "  -v     : verbose mode"
+  echo "  -h     : this help text"
 }
 
 PATS=()
 WHERE=.
-while getopts :cd:h opt
+unset VERBOSE
+while getopts :cd:vh opt
 do
   case "$opt" in
     c) PATS=(*.c *.cpp *.h) ;;
     d) WHERE=$OPTARG ;;
+    v) VERBOSE=1 ;;
     h) usage; exit ;;
     :) echo "Missing argument for '-$OPTARG'"; exit 22 ;;
-    *) echo "? Unknown argument: '-$OPTARG'"; exit 22 ;;
+    *) echo "Unknown argument: '-$OPTARG'"; exit 22 ;;
   esac
 done
 shift $((OPTIND-1))
 
 [[ $# -eq 0 ]] && { echo "Nothing specified"; exit 22; }
 
+if ! type -f rgrep > /dev/null 2>&1; then
+  echo "Unable to find required rgrep command"
+  exit 127
+fi
 
-set -x
+
+[[ -n $VERBOSE ]] && set -x
 exec rgrep $WHERE "$@" ${PATS[@]}
 
